# Generated by Django 5.1.6 on 2025-02-26 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_laptop_created_at_laptop_desctiption_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laptop',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='watch',
            options={'ordering': ['created_at']},
        ),
    ]
