# Generated by Django 5.1.6 on 2025-02-27 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_laptop_options_alter_phone_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laptop',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='watch',
            options={'ordering': ['-created_at']},
        ),
    ]
